# Generated by Django 6.0 on 2026-01-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
