# Generated by Django 6.0 on 2026-01-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
