# Generated by Django 6.0 on 2026-01-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_rename_description_projects_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='full_description',
            field=models.TextField(default='Project description will be updated soon.'),
        ),
        migrations.AddField(
            model_name='projects',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
