# Generated by Django 6.0 on 2026-01-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0008_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='describ',
            new_name='AboutMe',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='name',
            new_name='footer',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='intro',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to='resume_pdf/'),
        ),
        migrations.AddField(
            model_name='intro',
            name='introduction',
            field=models.TextField(default='Hi'),
        ),
        migrations.AddField(
            model_name='intro',
            name='logo_name',
            field=models.CharField(default='Your Name', max_length=20),
        ),
        migrations.AddField(
            model_name='intro',
            name='profile_name',
            field=models.CharField(default='Your Name', max_length=20),
        ),
    ]
