# Generated by Django 6.0 on 2026-01-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0009_delete_about_rename_describ_intro_aboutme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkdin', models.URLField(blank=True, null=True)),
                ('whatapp', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('email', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
