# Generated by Django 6.0 on 2026-01-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0010_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
