# Generated by Django 6.0 on 2026-01-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0011_alter_socialmedia_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='linkdin',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='whatapp',
            new_name='whatsapp',
        ),
    ]
