# Generated by Django 6.0 on 2026-01-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0012_rename_linkdin_socialmedia_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_title', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('institution_name', models.CharField(max_length=100)),
            ],
        ),
    ]
