# Generated by Django 6.0 on 2026-01-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0013_academic_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_qualification',
            name='board',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
