# Generated by Django 6.0 on 2026-01-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0014_academic_qualification_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_qualification',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
