# Generated by Django 6.0 on 2026-01-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0015_alter_academic_qualification_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_qualification',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
