# Generated by Django 6.0 on 2026-01-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0017_academic_certificates_academic_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Academic_Certificates',
            new_name='Academic_Certificate',
        ),
    ]
