# Generated by Django 6.0 on 2026-01-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0019_alter_academic_result_cgpa_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_title', models.CharField(max_length=50)),
                ('resume_pdf', models.FileField(upload_to='resume/')),
            ],
        ),
    ]
