# Generated by Django 6.0 on 2026-01-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0021_academic_result_result_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_certificate',
            name='certificate_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificate_pdf/'),
        ),
    ]
