# Generated by Django 6.0 on 2026-01-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0022_academic_certificate_certificate_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('project_overview', models.TextField(default='Project description will be updated soon.')),
                ('tech_stacks_title', models.TextField(default='techStack_title')),
                ('tech_stack_lists', models.TextField(default='techStack_list')),
                ('project_challenges', models.TextField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('live_demo', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
