# Generated by Django 6.0 on 2026-01-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0023_project_rename_skills_skill_delete_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_image/'),
        ),
    ]
