# Generated by Django 6.0 on 2026-01-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0025_techstack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_stack_lists',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_stacks_title',
        ),
    ]
