# Generated by Django 6.0 on 2026-01-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0026_remove_project_tech_stack_lists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='highlights',
            field=models.TextField(default='No highlights added yet.'),
        ),
    ]
