# Generated by Django 6.0 on 2026-01-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0027_project_highlights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic_qualification',
            name='description',
        ),
    ]
