# Generated by Django 6.0.1 on 2026-01-28 12:49

import myportfolio.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0029_rename_cgpa_value_academic_result_sgpa_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_certificate',
            name='certificate_pdf',
            field=models.ImageField(blank=True, null=True, storage=myportfolio.storages.ImageStorage(), upload_to='certificate_pdf/'),
        ),
        migrations.AlterField(
            model_name='academic_result',
            name='result_pdf',
            field=models.ImageField(blank=True, null=True, storage=myportfolio.storages.ImageStorage(), upload_to='result_pdf/'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='Resume',
            field=models.ImageField(blank=True, null=True, storage=myportfolio.storages.ImageStorage(), upload_to='resume_pdf/'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=myportfolio.storages.ImageStorage(), upload_to='myimage/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, storage=myportfolio.storages.ImageStorage(), upload_to='project_image/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_pdf',
            field=models.ImageField(storage=myportfolio.storages.ImageStorage(), upload_to='resume/'),
        ),
    ]
