# Generated by Django 6.0.1 on 2026-01-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0030_alter_academic_certificate_certificate_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic_certificate',
            name='certificate_platform_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_demo',
        ),
    ]
