# Generated by Django 6.0.1 on 2026-01-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0031_remove_academic_certificate_certificate_platform_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='whatsapp',
        ),
    ]
