# Generated by Django 6.0.1 on 2026-01-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0032_remove_socialmedia_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
